services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://10.3.57.68:8201
    container_name: frontend-mvp
    ports:
      - "3001:3000"
    env_file:
      - .env
    networks:
      - mvp-net
    restart: unless-stopped
    stdin_open: true
    tty: true

networks:
  mvp-net:
    external: true
